services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: timemanager
      MARIADB_USER: timemanager
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: mysql://timemanager:${MARIADB_PASSWORD}@db:3306/timemanager
      LDAP_URL: ${LDAP_URL}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_PASSWORD: ${LDAP_BIND_PASSWORD}
      LDAP_USER_FILTER: ${LDAP_USER_FILTER}
      LDAP_CA_CERT_PATH: /app/certs/primebank-root-ca.cer
      LDAP_TLS_SERVERNAME: ${LDAP_TLS_SERVERNAME}
      LDAP_DIRECT_BIND: ${LDAP_DIRECT_BIND}
      LDAP_UPN_DOMAIN: ${LDAP_UPN_DOMAIN}
      AD_SYNC_ENABLED: "true"
      AD_SYNC_INTERVAL_MINUTES: "2"
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL_MINUTES: "15"
      REFRESH_TTL_DAYS: "14"
      COOKIE_SECURE: "true"
    depends_on:
      - db
    expose:
      - "3000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    expose:
      - "5173"
    restart: unless-stopped

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/app.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  db-data:
